//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public author()
        {
            this.books = new HashSet<books>();
        }


        public int author_id { get; set; }

        [Required(ErrorMessage = "Please enter name.")]
        [MaxLength(50, ErrorMessage = "Author name cannot be longer than 50 character.")]
        public string author_name { get; set; }

        [Required(ErrorMessage = "Please enter surname.")]
        [MaxLength(50, ErrorMessage = "Author surname cannot be longer than 50 character.")]
        public string author_surname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<books> books { get; set; }
    }
}
