//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryManagementSystem.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_LIBRARYEntities : DbContext
    {
        public DB_LIBRARYEntities()
            : base("name=DB_LIBRARYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<author> author { get; set; }
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<fines> fines { get; set; }
        public virtual DbSet<members> members { get; set; }
        public virtual DbSet<publishers> publishers { get; set; }
        public virtual DbSet<safe> safe { get; set; }
        public virtual DbSet<schools> schools { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<transactions> transactions { get; set; }
    }
}
