//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public members()
        {
            this.fines = new HashSet<fines>();
            this.transactions = new HashSet<transactions>();
        }
    
        public int member_id { get; set; }
        public string member_name { get; set; }
        public string member_surname { get; set; }
        public string mail { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string phone_number { get; set; }
        public int school { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fines> fines { get; set; }
        public virtual schools schools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transactions> transactions { get; set; }
    }
}
