//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transactions()
        {
            this.fines = new HashSet<fines>();
        }
    
        public int id { get; set; }
        public int book { get; set; }
        public int member { get; set; }
        public int employee { get; set; }
        public Nullable<System.DateTime> taken_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<System.DateTime> member_return_date { get; set; }
        public bool transaction_status { get; set; }
    
        public virtual books books { get; set; }
        public virtual employees employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fines> fines { get; set; }
        public virtual members members { get; set; }
    }
}
